name: Release Vibe CLI

on:
  push:
    tags:
      - "v*" # Only trigger on version tags like v1.0.0

jobs:
  build:
    name: Build & Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller python-dotenv openai

      - name: Build binary with PyInstaller
        run: pyinstaller --onefile vibe.py

      - name: Rename binary
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/vibe.exe vibe-windows.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/vibe vibe-macos
          else
            mv dist/vibe vibe-linux
          fi

      - name: Create ZIPs
        if: runner.os != 'Windows'
        run: zip vibe-${{ runner.os }}.zip vibe-${{ runner.os }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vibe-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
